name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.11"

    name: Python ${{ matrix.python-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: template

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Scaffold Python package
        run: |
          pipx install cruft
          cruft create --no-input --extra-context '{"package_name": "My Package", "python_version": "${{ matrix.python-version }}", "with_typer_cli": "1"}' ./template/
          git init

      - name: Set up Poetry
        run: pipx install poetry==1.7.1

      - name: Install package
        run: poetry install
        working-directory: ./my-package/

      - name: Lint package
        run: poetry run poe lint
        working-directory: ./my-package/

      - name: Test package
        run: poetry run poe test
        working-directory: ./my-package/

      - name: Test building docs
        run: poetry run poe docs
        working-directory: ./my-package/
